config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :chats
  resources :locations
  resources :notifications
  resources :solicituds
  resources :amigos
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   namespace 'api' do
         post 'users/login', to: 'users#login'
         post 'users/login_token', to: 'users#login_token'
         get 'users/get_username_foto', to: 'users#get_username_foto'
         get 'users/search', to: 'users#search'
         post 'users/search_button', to: 'users#search_button'
         post 'posts/create', to: 'posts#create'
         get 'posts/get_friend_posts', to: 'posts#get_friend_posts'
         get 'amigos/get_amigos', to: 'amigos#get_amigos'
         post 'solicituds/create', to: 'solicituds#create'
         post 'solicituds/aceptar', to: 'solicituds#aceptar'
         delete 'solicituds/delete', to: 'solicituds#delete'
         get 'notifications/get', to: 'notifications#get'
         put 'notifications/set_false', to: 'notifications#set_false'
         get 'locations/get_friends_locations', to: 'locations#get_friends_locations'
         post 'locations/create', to: 'locations#create'
         post 'users/register', to: 'users#register'
         put 'users/change_user', to: 'users#change_user'
         put 'users/change_pass', to: 'users#change_pass'
         get 'posts/get_posts', to: 'posts#get_posts'
         get 'chats/get', to: 'chats#get'
         put 'chats/set_true', to: 'chats#set_true'
         get 'chats/get_chat_messages', to: 'chats#get_chat_messages'
         post 'chats/send_message', to: 'chats#send_message'
         get 'solicituds/get', to: 'solicituds#get'
         put 'users/update_image', to: 'users#update_image'
     end
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/controllers/api/notifications_controller.rb
module Api
  class NotificationsController < ApplicationController
    protect_from_forgery with: :null_session

    def get
      user = User.where(id: params[:id]).first

      if(user)
        notif = Notification.where(id_user: user.id)
        notif.order("created_at DESC")
        render json: { status: 'SUCCESS', message: 'Notificaciones obtenidas', notificaciones: notif}, status: :ok
      else
        render json: { status: 'INVALID', message: 'Error al obtener notificaciones'}, status: :unauthorized
      end
    end

    def set_false
      user = User.where(id: params[:id]).first

      if(user)
        notificaciones = Notification.where(id_user: user.id)
        notificaciones.each do |notif|
          notif.visto = true
          notif.save
        end

        render json: { status: 'SUCCESS', message: 'Notificaciones modificadas'}, status: :ok
      else
        render json: { status: 'INVALID', message: 'Error al modificar notificaciones'}, status: :unauthorized
      end
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:id_user, :id_friend, :id_post, :visto)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(notification) do |f| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_user %>
    <%= f.number_field :id_user %>
  </div>

  <div class="field">
    <%= f.label :id_friend %>
    <%= f.number_field :id_friend %>
  </div>

  <div class="field">
    <%= f.label :id_post %>
    <%= f.number_field :id_post %>
  </div>

  <div class="field">
    <%= f.label :visto %>
    <%= f.check_box :visto %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Id user</th>
      <th>Id friend</th>
      <th>Id post</th>
      <th>Visto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.id_user %></td>
        <td><%= notification.id_friend %></td>
        <td><%= notification.id_post %></td>
        <td><%= notification.visto %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id user:</strong>
  <%= @notification.id_user %>
</p>

<p>
  <strong>Id friend:</strong>
  <%= @notification.id_friend %>
</p>

<p>
  <strong>Id post:</strong>
  <%= @notification.id_post %>
</p>

<p>
  <strong>Visto:</strong>
  <%= @notification.visto %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>