config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :chats
  resources :locations
  resources :notifications
  resources :solicituds
  resources :amigos
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   namespace 'api' do
         post 'users/login', to: 'users#login'
         post 'users/login_token', to: 'users#login_token'
         get 'users/get_username_foto', to: 'users#get_username_foto'
         get 'users/search', to: 'users#search'
         post 'users/search_button', to: 'users#search_button'
         post 'posts/create', to: 'posts#create'
         get 'posts/get_friend_posts', to: 'posts#get_friend_posts'
         get 'amigos/get_amigos', to: 'amigos#get_amigos'
         post 'solicituds/create', to: 'solicituds#create'
         post 'solicituds/aceptar', to: 'solicituds#aceptar'
         delete 'solicituds/delete', to: 'solicituds#delete'
         get 'notifications/get', to: 'notifications#get'
         put 'notifications/set_false', to: 'notifications#set_false'
         get 'locations/get_friends_locations', to: 'locations#get_friends_locations'
         post 'locations/create', to: 'locations#create'
         post 'users/register', to: 'users#register'
         put 'users/change_user', to: 'users#change_user'
         put 'users/change_pass', to: 'users#change_pass'
         get 'posts/get_posts', to: 'posts#get_posts'
         get 'chats/get', to: 'chats#get'
         put 'chats/set_true', to: 'chats#set_true'
         get 'chats/get_chat_messages', to: 'chats#get_chat_messages'
         post 'chats/send_message', to: 'chats#send_message'
         get 'solicituds/get', to: 'solicituds#get'
         put 'users/update_image', to: 'users#update_image'
     end
end

app/models/amigo.rb
class Amigo < ApplicationRecord
end

app/controllers/amigos_controller.rb
class AmigosController < ApplicationController
  before_action :set_amigo, only: [:show, :edit, :update, :destroy]

  # GET /amigos
  # GET /amigos.json
  def index
    @amigos = Amigo.all
  end

  # GET /amigos/1
  # GET /amigos/1.json
  def show
  end

  # GET /amigos/new
  def new
    @amigo = Amigo.new
  end

  # GET /amigos/1/edit
  def edit
  end

  # POST /amigos
  # POST /amigos.json
  def create
    @amigo = Amigo.new(amigo_params)

    respond_to do |format|
      if @amigo.save
        format.html { redirect_to @amigo, notice: 'Amigo was successfully created.' }
        format.json { render :show, status: :created, location: @amigo }
      else
        format.html { render :new }
        format.json { render json: @amigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amigos/1
  # PATCH/PUT /amigos/1.json
  def update
    respond_to do |format|
      if @amigo.update(amigo_params)
        format.html { redirect_to @amigo, notice: 'Amigo was successfully updated.' }
        format.json { render :show, status: :ok, location: @amigo }
      else
        format.html { render :edit }
        format.json { render json: @amigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amigos/1
  # DELETE /amigos/1.json
  def destroy
    @amigo.destroy
    respond_to do |format|
      format.html { redirect_to amigos_url, notice: 'Amigo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amigo
      @amigo = Amigo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amigo_params
      params.require(:amigo).permit(:id_user1, :id_user2)
    end
end

app/controllers/api/amigos_controller.rb
module Api
  class AmigosController < ApplicationController
    protect_from_forgery with: :null_session

    def get_amigos
      user = User.where(id: params[:id]).first
      if(user)
        amigos = Amigo.where(id_user1: user.id)

        lista_amigos = []
        amigos.each do |amigo|
          usuario = User.where(id: amigo.id_user2).first
          if(usuario)
            lista_amigos.push(usuario)
          end
        end
        render json: { status: 'SUCCESS', message: 'Amigos obtenidos', amigos: lista_amigos}, status: :ok

      else
        render json: { status: 'INVALID', message: 'Error al obtener los amigos'}, status: :unauthorized
      end
    end

  end
end

app/helpers/amigos_helper.rb
module AmigosHelper
end

app/views/amigos/_form.html.erb
<%= form_for(amigo) do |f| %>
  <% if amigo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(amigo.errors.count, "error") %> prohibited this amigo from being saved:</h2>

      <ul>
      <% amigo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_user1 %>
    <%= f.number_field :id_user1 %>
  </div>

  <div class="field">
    <%= f.label :id_user2 %>
    <%= f.number_field :id_user2 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/amigos/edit.html.erb
<h1>Editing Amigo</h1>

<%= render 'form', amigo: @amigo %>

<%= link_to 'Show', @amigo %> |
<%= link_to 'Back', amigos_path %>

app/views/amigos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Amigos</h1>

<table>
  <thead>
    <tr>
      <th>Id user1</th>
      <th>Id user2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amigos.each do |amigo| %>
      <tr>
        <td><%= amigo.id_user1 %></td>
        <td><%= amigo.id_user2 %></td>
        <td><%= link_to 'Show', amigo %></td>
        <td><%= link_to 'Edit', edit_amigo_path(amigo) %></td>
        <td><%= link_to 'Destroy', amigo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amigo', new_amigo_path %>

app/views/amigos/new.html.erb
<h1>New Amigo</h1>

<%= render 'form', amigo: @amigo %>

<%= link_to 'Back', amigos_path %>

app/views/amigos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id user1:</strong>
  <%= @amigo.id_user1 %>
</p>

<p>
  <strong>Id user2:</strong>
  <%= @amigo.id_user2 %>
</p>

<%= link_to 'Edit', edit_amigo_path(@amigo) %> |
<%= link_to 'Back', amigos_path %>